services:
  mittel.db:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password # Remova ou ajuste se necessário
    restart: always
    ports:
      - '3307:3306'
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mittel
    volumes:
      - mysql.mittel:/var/lib/mysql
volumes:
  mysql.mittel:
